spring:
  devtools:
    restart:
      enabled: true
      trigger-file: .reloadtrigger
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true

  application:
    name: springboot-api

  datasource:
    url: jdbc:postgresql://localhost:5432/notebooks
    username: admin
    password: Admin1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

# ==============================
# Custom properties cho pgvector
# ==============================
vector:
  embedding-dimension: 1536

# ==============================
# Server port
# ==============================
server:
  port: 8386
