spring:
  devtools:
    restart:
      enabled: true
      trigger-file: .reloadtrigger
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true

  application:
    name: springboot-api

  datasource:
    url: jdbc:postgresql://localhost:5432/notebook
    username: postgres
    password: 88888888

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

vector:
  embedding-dimension: 1536

server:
  port: 8386

file:
  upload-dir: uploads
  base-url: http://localhost:8386

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    enabled: true

gemini:
  api-key: AIzaSyAcPcb1MacdXNXxcoMgaavp8G7ovGs-9xU
